#!/usr/bin/with-contenv ash

touch /etc/dnsmasq-resolv.conf

echo "Waiting for dnsmasq"
while ! ps -ef | grep -v grep | grep dnsmasq-resolv.conf  &> /dev/null
do
    sleep 1
done

echo "Starting DNS monitoring loop"
while true
do
    if  ( cat /etc/resolv.conf | grep "nameserver 127.0.0.1" &> /dev/null )
    then
        sleep 30
    else
        cp -f /etc/resolv.conf /etc/dnsmasq-resolv.conf
        echo "nameserver 127.0.0.1" > /etc/resolv.conf
    fi

    . /bin/dns_hack.sh
    . /bin/additional_hosts.sh

     if ! diff /tmp/hosts /etc/hosts.links
     then
        echo "Updating DNS values"
        cp -f /tmp/hosts /etc/hosts.links
        cp  /etc/hosts.orig /etc/hosts
        killall -HUP dnsmasq  &> /dev/null
     else
        echo "No change to DNS values"
     fi
     sleep 5
done
