#!/bin/sh -x
if [ ! -f /etc/dnsmasq-resolv.conf ]
then
    cp -f /etc/resolv.conf /etc/dnsmasq-resolv.conf
    echo "nameserver 127.0.0.1" > /etc/resolv.conf
fi
exec dnsmasq ${DNSMASQ_ARGS:- --server=/node.tutum.io/162.159.24.22 --server=/cont.tutum.io/162.159.24.22 --server=/svc.tutum.io/162.159.25.72} --no-daemon 2>&1 | logger